In [ ]:
# Creating an empty array

In [3]:
import numpy as np 

In [7]:
array_empty = np.empty((2,3))


In [8]:
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Creating an identity matrix in numpy

In [9]:
array_eye = np.eye(4)  # identity matrix is a matrix which have 1s in diagonal

array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Req : print the even numbers till 20 

In [10]:
array_of_evens = np.arange(2,20,2) #2

array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# will it accept the float arguments as well ... (decimals)

In [13]:
array_of_floats = np.arange(0,3,0.3)

array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

In [ ]:
# x ==> 1 dimension array

# (x,y) ==> 2 dimensional array

# (x,y,z) ==> 3 dimensional array



In [14]:
array_2d = np.array([(2,4,6),(3,5,7)])

array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [15]:
array_2d.shape # (x,y)

(2, 3)

In [16]:
array_2d.ndim

2

In [ ]:
# using reshape to create n dimensional arrays

In [17]:
x = np.arange(6) # 1 dimensional array

x

array([0, 1, 2, 3, 4, 5])

In [18]:
x = np.arange(6).reshape(3,2)  # Reshape value should match the arange value eg. 3*2 =6

                                # if reshape value exceeds the arrange value it results an error
x


array([[0, 1],
       [2, 3],
       [4, 5]])

In [19]:
x = np.arange(6).reshape(3,3) 

x

ValueError: cannot reshape array of size 6 into shape (3,3)