In [ ]:
Introduction to 3rd party libraries in Python

In [ ]:
Numpy: Numpy stands for numerical python. it is a foundational library to make the AI, ML, DL algorithms to work smoothly.
    it is also used for scientific computations.
    

In [ ]:
installation of Numpy : 
    by executing the command we can install numpy
    !pip install numpy
    

In [1]:
!pip install numpy

In [ ]:
Datatypes in Numpy:
    It is having a datatype called ndarray
    ndarray --> N dimensional arrays
    
    

In [ ]:
1. Creating an array from regular python list


In [2]:
import numpy as np #np is alias name. we can give any name; but np is commonly used all over the world

In [3]:
array_one = np.array([1,2,3,4])

In [4]:
array_one

array([1, 2, 3, 4])

In [5]:
type(array_one)

numpy.ndarray

In [6]:
numbers = [5,4,3,2]

In [7]:
array_two=np.array(numbers)

In [8]:
array_two

array([5, 4, 3, 2])

In [ ]:
Note: Array is similar to list.
    
    Interview Question: Given an array and list.. what will you chose?
        which one having high performance?
        
        Answer : Array; As internal implementation of sorting the data is optimized and 
                    retrieves the data in a faster manner
            
            

In [ ]:
# Creating an array of zero with desired shape (x,y)

# x =  no. of rows
# y = no. of cols

In [10]:
array_of_zeros = np.zeros((3,4)) #x,y

In [11]:
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# Create an array of ones

In [13]:
array_of_ones = np.ones((3,4))
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Note : Internal implementation of array is float (decimals), integers and float (decimals)

# therefore the array is filled with float values... to get the numbers in int refer below

In [15]:
array_of_ones_int =  np.ones((4,5), dtype=np.int16) #  int16, int32, int64 are the integer formats

In [16]:
array_of_ones_int

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)